#!/usr/bin/env python3
"""Generate #main typography-only locale scale overrides from template CSS."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CSS_IN = ROOT / "public" / "dist" / "style.min.css"
CSS_OUT = ROOT / "public" / "features" / "roots-locale-type-scale.css"

SKIP_SUBSTRINGS = (
    ".nav",
    "cookie",
    "preloader",
    "loader",
    "homeheader",
)


def should_skip_part(part: str) -> bool:
    low = part.strip().lower()
    if low in {"html", "body"}:
        return True
    return any(sub in low for sub in SKIP_SUBSTRINGS)


def should_skip(selector: str) -> bool:
    parts = [p.strip() for p in selector.split(",")]
    if not parts:
        return True
    return all(should_skip_part(part) for part in parts)


def scale_font_size(value: str) -> str | None:
    value = value.strip()
    if "var(" in value:
        return None
    if any(
        token in value
        for token in ("rem", "em", "vw", "vh", "dvh", "clamp", "min(", "max(")
    ):
        return f"calc({value} * var(--roots-type-scale))"
    return None


def split_media_blocks(source: str) -> list[tuple[str, str]]:
    blocks: list[tuple[str, str]] = [("", source)]
    result: list[tuple[str, str]] = []
    for media, chunk in blocks:
        pos = 0
        while pos < len(chunk):
            match = re.search(r"@media[^{]+\{", chunk[pos:])
            if not match:
                result.append((media, chunk[pos:]))
                break
            start = pos + match.start()
            if start > pos:
                result.append((media, chunk[pos:start]))
            header_end = pos + match.end()
            depth = 1
            i = header_end
            while i < len(chunk) and depth:
                if chunk[i] == "{":
                    depth += 1
                elif chunk[i] == "}":
                    depth -= 1
                i += 1
            inner = chunk[header_end : i - 1]
            media_query = chunk[start:header_end - 1].strip()
            result.append((media_query, inner))
            pos = i
    return result


def extract_rules(block: str) -> list[tuple[str, str, str]]:
    rules: list[tuple[str, str, str]] = []
    for match in re.finditer(r"([^{}]+)\{([^{}]+)\}", block):
        selector, body = match.group(1).strip(), match.group(2)
        if should_skip(selector):
            continue
        font_match = re.search(r"font-size\s*:\s*([^;!]+)", body)
        if not font_match:
            continue
        original = font_match.group(1).strip()
        scaled = scale_font_size(original)
        if not scaled:
            continue
        scoped_parts = []
        for part in selector.split(","):
            part = part.strip()
            if should_skip_part(part):
                continue
            if part.startswith("#main"):
                scoped = part
            else:
                scoped = f"#main {part}"
            scoped_parts.append(scoped)
        if not scoped_parts:
            continue
        rules.append((scoped_parts, original, scaled))
    return rules


def main() -> None:
    source = CSS_IN.read_text(encoding="utf-8", errors="ignore")
    grouped: dict[str, list[tuple[str, str, str]]] = {}
    for media, block in split_media_blocks(source):
        for rule in extract_rules(block):
            grouped.setdefault(media, []).append(rule)

    lines = [
        "/*",
        " * Typography-only locale scale for #main (hy/ru vs EN).",
        " * Generated by dev/scripts/generate-locale-type-scale-css.py — do not hand-edit.",
        " * html vw stays at EN so rem layout (nav, cards, spacing) is unchanged.",
        " */",
        "",
    ]

    for media in grouped:
        rules = grouped[media]
        seen: set[str] = set()
        unique_rules = []
        for scoped_parts, original, scaled in rules:
            key = f"{'|'.join(scoped_parts)}|{original}|{scaled}"
            if key in seen:
                continue
            seen.add(key)
            unique_rules.append((scoped_parts, original, scaled))

        if media:
            lines.append(f"{media} {{")
        for scoped_parts, _original, scaled in unique_rules:
            hy_sels = ",\n".join(f'html[lang="hy"] {part}' for part in scoped_parts)
            ru_sels = ",\n".join(f'html[lang="ru"] {part}' for part in scoped_parts)
            lines.append(f"{hy_sels},")
            lines.append(f"{ru_sels} {{")
            lines.append(f"    font-size: {scaled};")
            lines.append("}")
            lines.append("")
        if media:
            lines.append("}")
            lines.append("")

    CSS_OUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {CSS_OUT} ({len(lines)} lines, {sum(len(v) for v in grouped.values())} rules)")


if __name__ == "__main__":
    main()
